---
# This is an indexer configuration file for a mirror called "local".
mirror: file:///home/fgabolde/work/localpinto/
workdir: /home/fgabolde/work/local-dist-data/
state: path/to/state.storable
base-url: http://localhost:5000/wherever/mirror/local/
dsn: dbi:SQLite:path/to/foo.db
